import { makeConsumable, makeWeapon } from '../loot/lootTables';
import type { SlotItem } from '../inventory/items';
import type { ModeConfig, ModeId } from './matchTypes';

const fullLoadout = (): SlotItem[] => [
  makeWeapon('shotgun', 'elite') as SlotItem,
  makeWeapon('ar', 'elite') as SlotItem,
  makeWeapon('smg', 'elite') as SlotItem,
  makeWeapon('marksman', 'elite') as SlotItem,
  makeConsumable('shield_cell', 6) as SlotItem,
];

/** Data-driven mode definitions. */
export const MODES: Record<ModeId, ModeConfig> = {
  br: {
    id: 'br',
    name: 'Battle Royale',
    tagline: 'Drop in. Loot up. Outlast 15 bots.',
    description: 'Deploy over Hollow Ridge, scavenge weapons and materials, build to survive and be the last one standing as the storm collapses.',
    map: 'hollow_ridge',
    mapName: 'Hollow Ridge',
    maxPlayers: 16,
    bots: 15,
    storm: true,
    loot: true,
    deployment: true,
    materials: { wood: 0, stone: 0, metal: 0 },
    unlimitedAmmo: false,
    loadout: [],
    startShield: 0,
    fallDamage: true,
    roundsToWin: 0,
    respawn: 'none',
    durationLabel: '8–12 min',
    accent: '#5ee7ff',
    training: false,
  },
  duel: {
    id: 'duel',
    name: 'Duel',
    tagline: 'Competitive 1v1 build fight.',
    description: 'Full loadout, high material cap, first elimination wins. Built for fast rematches.',
    map: 'duel_arena',
    mapName: 'Neon Proving Ground',
    maxPlayers: 2,
    bots: 1,
    storm: false,
    loot: false,
    deployment: false,
    materials: { wood: 500, stone: 500, metal: 500 },
    unlimitedAmmo: true,
    loadout: fullLoadout(),
    startShield: 100,
    fallDamage: false,
    roundsToWin: 1,
    respawn: 'round',
    durationLabel: '1–3 min',
    accent: '#ff5ad1',
    training: false,
  },
  boxfight: {
    id: 'boxfight',
    name: 'Box Fight',
    tagline: 'Close quarters. Edits win.',
    description: 'Both players start inside a box. Limited materials, limited loot — first to 3 rounds takes the match.',
    map: 'box_arena',
    mapName: 'The Crate',
    maxPlayers: 2,
    bots: 1,
    storm: false,
    loot: false,
    deployment: false,
    materials: { wood: 200, stone: 100, metal: 0 },
    unlimitedAmmo: true,
    loadout: [
      makeWeapon('shotgun', 'prime') as SlotItem,
      makeWeapon('smg', 'prime') as SlotItem,
      makeWeapon('ar', 'prime') as SlotItem,
      makeConsumable('shield_cell', 3) as SlotItem,
    ],
    startShield: 50,
    fallDamage: false,
    roundsToWin: 3,
    respawn: 'round',
    durationLabel: '3–5 min',
    accent: '#ff9d2e',
    training: false,
  },
  zonewar: {
    id: 'zonewar',
    name: 'Zone War',
    tagline: 'Rotate, build, survive the moving zone.',
    description: 'Eight players, a fast-moving storm and a full loadout. Win two rounds to take the match.',
    map: 'zone_arena',
    mapName: 'Shifting Hills',
    maxPlayers: 8,
    bots: 7,
    storm: true,
    loot: false,
    deployment: false,
    materials: { wood: 400, stone: 300, metal: 200 },
    unlimitedAmmo: true,
    loadout: fullLoadout(),
    startShield: 100,
    fallDamage: true,
    roundsToWin: 2,
    respawn: 'round',
    durationLabel: '4–8 min',
    accent: '#c257ff',
    training: false,
  },
  freebuild: {
    id: 'freebuild',
    name: 'Freebuild',
    tagline: 'Unlimited practice sandbox.',
    description: 'Infinite materials and ammo, every weapon, target dummies, edit walls and training stations. Reset builds any time.',
    map: 'training_grounds',
    mapName: 'Training Grounds',
    maxPlayers: 1,
    bots: 0,
    storm: false,
    loot: false,
    deployment: false,
    materials: 'unlimited',
    unlimitedAmmo: true,
    loadout: fullLoadout(),
    startShield: 100,
    fallDamage: false,
    roundsToWin: 0,
    respawn: 'manual',
    durationLabel: 'Unlimited',
    accent: '#3ccf8e',
    training: true,
  },
  tutorial: {
    id: 'tutorial',
    name: 'Tutorial',
    tagline: 'Learn the basics.',
    description: 'A guided walkthrough of moving, shooting, building and editing.',
    map: 'training_grounds',
    mapName: 'Training Grounds',
    maxPlayers: 1,
    bots: 0,
    storm: false,
    loot: false,
    deployment: false,
    materials: 'unlimited',
    unlimitedAmmo: true,
    loadout: [makeWeapon('shotgun', 'prime') as SlotItem, makeWeapon('ar', 'prime') as SlotItem],
    startShield: 0,
    fallDamage: false,
    roundsToWin: 0,
    respawn: 'manual',
    durationLabel: '5 min',
    accent: '#3ccf8e',
    training: true,
  },
};

export const PLAYABLE_MODES: ModeId[] = ['br', 'duel', 'boxfight', 'zonewar', 'freebuild'];

export const BOT_NAMES = [
  'Rook', 'Nova', 'Mako', 'Cipher', 'Echo', 'Vex', 'Raven', 'Atlas', 'Drift', 'Pulse', 'Ghost', 'Kite', 'Onyx', 'Flint', 'Wisp',
  'Sable', 'Juno', 'Tarn', 'Quill', 'Bolt', 'Ember', 'Lark', 'Moss', 'Rune',
];
