import { chromium } from 'playwright';
const url = process.argv[2] ?? 'http://localhost:5173/';
const out = process.argv[3] ?? '/tmp/claude-0';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const logs = [];
page.on('console', (m) => { if (!['debug'].includes(m.type())) logs.push(`[${m.type()}] ${m.text()}`); });
page.on('pageerror', (e) => logs.push(`[pageerror] ${e.message}\n${e.stack}`));
await page.addInitScript(() => localStorage.setItem('robnite.save', JSON.stringify({ version: 1, profileCreated: true, profile: { displayName: 'Tester' }, login: { lastDay: 99999999, streak: 1 }, tutorial: { offered: true } })));
await page.goto(url);
await page.waitForSelector('.btn-play', { timeout: 30000 });
const t0 = Date.now();
await page.evaluate(() => window.robnite.startMatch('br', 'normal'));
await page.waitForTimeout(1200);
await page.screenshot({ path: `${out}/br-loading.png` });
await page.waitForSelector('.click-to-play', { timeout: 120000 });
logs.push(`load ms ${Date.now() - t0}`);
await page.click('.click-to-play');
await page.waitForTimeout(1500);
await page.screenshot({ path: `${out}/br-warmup.png` });
// Fast-forward the simulation to deployment, jump and teleport near a POI for a look.
await page.evaluate(() => {
  const c = window.robnite.client;
  const m = c.match;
  for (let i = 0; i < 60 * 6; i++) m.step(1 / 60);
  m.queueAction(0, { type: 'jumpFromBus' });
  m.step(1 / 60);
  const h = m.human;
  h.pos.set(-95, 60, 70);
});
await page.waitForTimeout(2500);
await page.screenshot({ path: `${out}/br-glide.png` });
await page.evaluate(() => {
  const m = window.robnite.client.match;
  for (let i = 0; i < 60 * 8; i++) m.step(1 / 60);
});
await page.waitForTimeout(2000);
await page.screenshot({ path: `${out}/br-town.png` });
const fps = await page.evaluate(() => window.robnite.client.fps);
logs.push(`fps ${fps}`);
await page.keyboard.press('KeyM');
await page.waitForTimeout(600);
await page.screenshot({ path: `${out}/br-map.png` });
console.log(logs.join('\n'));
await browser.close();
